name: 'Release tag tracker'
author: 'Benjamin Wuethrich'
description: 'Update tags pointing to latest major and minor releases'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'tag'
  color: 'blue'
