name: Release tag tracker
author: Benjamin Wuethrich
description: Update tags pointing to latest major and minor releases
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/tagupdater
