#!/usr/bin/env bash

# List all semver tags minus the "v" and sort them
gettags() {
	git tag \
		| sed -rn 's/v(([[:digit:]]+\.){2}[[:digit:]]+)/\1/p' \
		| sort -t. -n -k1,1 -k2,2 -k3,3
}

# Build associative array of most recent major and minor releases
declare -A latest

while IFS=. read -r major minor patch; do
	latest[v"$major"]="v$major.$minor.$patch"
	latest[v"$major.$minor"]="v$major.$minor.$patch"
done <<< "$(gettags)"

for key in "${!latest[@]}"; do
	echo "$key --> ${latest["$key"]}"
done

# Check if branches for most recent minor and major tags exist
# Create new branches at most recent tags without branch
# For existing branches, fast-forward merge to most recent applicable tag
