#!/usr/bin/env bash

set -o errexit -x

# List all semver tags minus the "v" and sort them; busybox sort doesn't have
# version sort
gettags() {
	git tag \
		| sed -rn 's/v(([[:digit:]]+\.){2}[[:digit:]]+)/\1/p' \
		| sort -t. -n -k1,1 -k2,2 -k3,3
}

# Set Git user and email to bot
git config user.name 'github-actions'
git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

# Suppress detached HEAD warning
git config advice.detachedHead false

# Clobber local tags
git fetch --tags --force

# Build associative array of most recent major and minor releases
declare -A latest

while IFS=. read -r major minor patch; do
	latest["v$major"]="v$major.$minor.$patch"
	latest["v$major.$minor"]="v$major.$minor.$patch"
done < <(gettags)

git remote set-url --push origin \
	"https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"

# Move or create tags
for tag in "${!latest[@]}"; do
	if git show-ref --tags --quiet "$tag"; then
		# Delete local and remote tag
		git tag --delete "$tag"
		git push --delete origin "$tag"
	fi
	git tag --annotate --message="Latest release in $tag" "$tag" "${latest["$tag"]}"^{}
done
git push origin "${!latest[@]}"
